### ISSUE TITLE
Add default image

### ISSUE THREAD

**Issue by dernoun** [zeeshux7860/ImageEditorPro#25]
There is a scenario where user want to edit an existing image inside it's app that doesn't exist on gallery or it's not photo, network image for example that's not stored on the phone.
Is there a way to handle this? so when user call the plugin, he could upload this image as default instead of the white image. Simple solution is adding an optional argument to  `ImageEditorPro` that's will be used to pass this image.

**Comment by AhmetHuseyinDOK** [comment]
I also need this feature

**Comment by CoderJava** [comment]
@dernoun @AhmetHuseyinDOK 
Hi all,
I have already added support for default image in this plugin.

**Comment by CodingWithTashi** [comment]
I see code is committed on july first, But I don't find the implmentation in the latest package. When can we expect the release.

**Comment by CodingWithTashi** [comment]
> @dernoun @AhmetHuseyinDOK
> Hi all,
> I have already added support for default image in this plugin. You can check the progress in this PR #32

Seems working fine in mobile devices with defaultImage as File type, But how do you expect to work in web since web require Uint8List type If possible add parameter to display in web condition as well.
Thanks

**Comment by riteshghimire9090** [comment]
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

**Comment by MayconProgramr** [comment]
Boa tarde

Algum retorno sobre essa implementação de imagem default?

**Comment by CodingWithTashi** [comment]
@MayconProgramr  Package seems inactive, You can use [CoderJava Repo for now to send default image](https://github.com/CoderJava/ImageEditorPro)

**Comment by CoderJava** [comment]
#4
