### ISSUE TITLE
Cannot open file n_structure_<.>.json

### ISSUE THREAD

**Issue by matthewmizzi** [zeeshux7860/ImageEditorPro#42]
Hello,

I am having an issue when adding this plugin that when I run the 'flutter pub add image_editor_pro' command stating that 

**Cannot open file, path = 'C:\Users\user\Documents\flutter\.pub-cache\_temp\dir3ec2f2b5\test\fixtures\invalid\n_structure_<.>.json' (OS Error: The filename, directory name, or volume label syntax is incorrect.**

**Comment by DKConvista** [comment]
Same error here after **flutter 2.5** upgrade. Downgrading to 2.2.3 solves it, if that is an option. Would be nice, if Flutter 2.5 would be supported in the future.

**Comment by matthewmizzi** [comment]
Thanks!
