### ISSUE TITLE
Importing Problem

### ISSUE THREAD

**Issue by shubhamhhum** [zeeshux7860/ImageEditorPro#8]
### When I import this in dependencies it gives me this error

```
[image_editor_pro] flutter pub get
Running "flutter pub get" in image_editor_pro...                
Error on line 31, column 3 of pubspec.yaml: A package may not list itself as a dependency.

   ╷

31 │   image_editor_pro:

   │   ^^^^^^^^^^^^^^^^

   ╵
pub get failed (65;    ╵)
exit code 65
```

**Comment by dernoun** [comment]
@shubhamhhum show all your `pubspec.yaml`, yaml file is sensitive on spaces.

**Comment by shubhamhhum** [comment]
I did this issue long ago. At that time I was learning flutter. This problem may have happened due to my internet connection. Now I have also deleted that project. **It is working now**.
